spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?allowPublicKeyRetrieval=true&useSSL=false
    driver-class: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    method:
      method-param:
        enabled: true

  profiles:
    include: oauth

logging:
  level:
    org:
      springframework:
        security: DEBUG






